{
  "hash": "da6c2795f20a9fa5ac3dccb93a47fc82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exercise 7: Annotation\"\nformat: html\neditor: source\neditor_options: \n  chunk_output_type: console\nexecute:\n  warning: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(scater)\nlibrary(SpatialExperiment)\nlibrary(SpatialFeatureExperiment)\nlibrary(Voyager)\nlibrary(DropletUtils)\nlibrary(SingleR)\nlibrary(tidyverse)\nlibrary(stringr)\nlibrary(patchwork)\nlibrary(viridis)\nlibrary(RColorBrewer)\nlibrary(pheatmap)\nlibrary(alabaster.sfe)\n```\n:::\n\n\n## Dataset loading\nWe will start by loading the segmented Visium HD dataset stored in the `SpatialFeatureExperiment` object generated in the previous exercise. It contains information on the non-spatially-aware and spatially-aware clusters computed with graph-based clustering Banksy and PCA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reload the SpatialFeatureExperiment object if not in the R session already\nsfe <- readObject(\"results/day2/02.3_sfe/\")\nsfe\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SpatialFeatureExperiment \ndim: 18878 33763 \nmetadata(2): resources spatialList\nassays(2): counts logcounts\nrownames(18878): OR4F5 SAMD11 ... DEPRECATED_ENSG00000291096\n  DEPRECATED_TRIM16L\nrowData names(5): ID Symbol Type subsets_Mito hvg\ncolnames(33763): cellid_000080404-1 cellid_000080411-1 ...\n  cellid_000189331-1 cellid_000189341-1\ncolData names(33): sample_id area ... Leiden Banksy\nreducedDimNames(5): PCA_artifacts PCA PCA_banksy UMAP UMAP_banksy\nmainExpName: Gene Expression\naltExpNames(0):\nspatialCoords names(2) : pxl_col_in_fullres pxl_row_in_fullres\nimgData names(4): sample_id image_id data scaleFactor\n\nunit: \nGeometries:\ncolGeometries: centroids (POINT), cellSeg (POLYGON) \n\nGraphs:\nsample01: \n```\n\n\n:::\n:::\n\n\nTo transfer cell-type labels to out Visium HD dataset, we will use a [matching scRNA-seq dataset](https://www.10xgenomics.com/platforms/visium/product-family/dataset-human-crc) generated by the 10X team for the same article. See the record on [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE280311).\n\n::: callout-important\n### Exercise 1\nWhich technology was used to generate the scRNA-seq dataset and how was the experiment designed?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Answer\nThis scRNA-seq was generated with the 10X FLEX technology, which is probe-based and allows to work with FFPE tissue blocks.\n\nSample barcodes, sequenced together with the probe sequences allow to pool multiple samples together and then demultiplex them. Here 2 pools of 2 samples (P2CRC/P4CRC, P3NAT/P5NAT) and 1 pool of 4 samples (P1CRC/P3CRC/P5CRC/P2NAT) were created, so 8 samples in total, and each pool was sequenced on multiple 10X Chromium lanes.\n:::\n\n## Download the FLEX dataset\n\nWe will download the scRNA-seq data from GEO, but this doesn't include the cell metadata, in particular the annotated cell type that we need here. This is available from Github: https://github.com/10XGenomics/HumanColonCancer_VisiumHD/tree/main\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(timeout = 1000)\n\nif (!dir.exists(\"data/FLEX/\")) {\n  download.file(\n    url = \"https://ftp.ncbi.nlm.nih.gov/geo/series/GSE280nnn/GSE280311/suppl/GSE280311_RAW.tar\",\n    destfile = \"data/GSE280311_RAW.tar\",\n    mode = \"wb\"\n  )\n  untar(\n    tarfile = \"data/GSE280311_RAW.tar\",\n    exdir = \"data/FLEX/\"\n  )\n  file.remove(\"data/GSE280311_RAW.tar\")\n\n  ## Download the cell metadata from 10X Github page\n  download.file(\n    url = \"https://raw.githubusercontent.com/10XGenomics/HumanColonCancer_VisiumHD/refs/heads/main/MetaData/SingleCell_MetaData.csv.gz\",\n    destfile = \"data/FLEX/SingleCell_MetaData.csv.gz\",\n    mode = \"wb\"\n  )\n} else {\n  message(\"Data exists, please proceed to next steps!\")\n}\n```\n:::\n\n\n\n## Load the P2CRC sample\n\nThe sample matching our Visium HD and Xenium dataset was sequenced on 4 10X channels. For simplicity here, we only load the cell from one channel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlist.files(\"data/FLEX/\", pattern = \"P2CRC\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GSM8594533_P1L1_P2CRC_BC1_count_filtered_feature_bc_matrix.h5\"\n[2] \"GSM8594534_P1L2_P2CRC_BC1_count_filtered_feature_bc_matrix.h5\"\n[3] \"GSM8594535_P1L3_P2CRC_BC1_count_filtered_feature_bc_matrix.h5\"\n[4] \"GSM8594536_P1L4_P2CRC_BC1_count_filtered_feature_bc_matrix.h5\"\n```\n\n\n:::\n\n```{.r .cell-code}\nref.sce <- DropletUtils::read10xCounts(\"data/FLEX/GSM8594533_P1L1_P2CRC_BC1_count_filtered_feature_bc_matrix.h5\")\nref.sce\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SingleCellExperiment \ndim: 18082 10397 \nmetadata(1): Samples\nassays(1): counts\nrownames(18082): ENSG00000187634 ENSG00000188976 ... ENSG00000198695\n  ENSG00000198727\nrowData names(3): ID Symbol Type\ncolnames: NULL\ncolData names(2): Sample Barcode\nreducedDimNames(0):\nmainExpName: NULL\naltExpNames(0):\n```\n\n\n:::\n\n```{.r .cell-code}\ncolnames(ref.sce) <- ref.sce$Barcode\n\nrownames(ref.sce) <- uniquifyFeatureNames(\n  ID = rowData(ref.sce)$ID,\n  names = rowData(ref.sce)$Symbol\n)\n\n## We will need the logcounts for the annotation\nref.sce <- logNormCounts(ref.sce)\n\nref.sce\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass: SingleCellExperiment \ndim: 18082 10397 \nmetadata(1): Samples\nassays(2): counts logcounts\nrownames(18082): SAMD11 NOC2L ... MT-ND6 MT-CYB\nrowData names(3): ID Symbol Type\ncolnames(10397): AAACAAGCAACAGCACACTTTAGG-1 AAACAAGCAACAGCTAACTTTAGG-1\n  ... TTTGTGAGTCGTTCGAACTTTAGG-1 TTTGTGAGTTTACCGGACTTTAGG-1\ncolData names(3): Sample Barcode sizeFactor\nreducedDimNames(0):\nmainExpName: NULL\naltExpNames(0):\n```\n\n\n:::\n:::\n\n\n::: callout-important\n### Exercise 2\nHow many cells were sequenced in this specific run? Why are counts available for only 18,082 genes? What type of information is available in the `colData`?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Answer\nWe loaded here 10,397 cells from one 10X channel run of the P2CRC sample (multiplexed with another channel).\n\nThe FLEX technology is probe-based so it doesn't cover the full transcriptome, mostly the protein-coding genes are targeted. \n\nSo far, there is no information on the cells in the object, expect their 10X barcode.\n:::\n\n## Load the annotation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncell_metadata <- read.csv(\"data/FLEX/SingleCell_MetaData.csv.gz\")\ndim(cell_metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 279609      8\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(cell_metadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     Barcode Patient  BC QCFilter      Level1      Level2\n1 AAACAAGCAACAGCACACTTTAGG-1   P2CRC BC1   Remove QC_Filtered QC_Filtered\n2 AAACAAGCAACAGCTAACTTTAGG-1   P2CRC BC1     Keep     B cells      Plasma\n3 AAACAAGCAACTGTTCACTTTAGG-1   P2CRC BC1     Keep     T cells  CD4 T cell\n4 AAACAAGCAAGGCCTGACTTTAGG-1   P2CRC BC1     Keep       Tumor   Tumor III\n5 AAACAAGCACATAGTGACTTTAGG-1   P2CRC BC1     Keep       Tumor   Tumor III\n6 AAACAAGCAGCATTTCACTTTAGG-1   P2CRC BC1     Keep     Myeloid  Macrophage\n        UMAP1      UMAP2\n1   3.9868812  4.3530427\n2 -10.4759963 -0.2676283\n3  11.0405902 -5.0512951\n4   0.4739105  3.7213750\n5   2.3165844  4.8091193\n6   6.3369237 -7.7051039\n```\n\n\n:::\n\n```{.r .cell-code}\ncell_metadata <- cell_metadata |>\n  as_tibble() |>\n  mutate(Sample = str_extract(Barcode, pattern = \"(\\\\d)$\")) |>\n  filter(Patient == \"P2CRC\" & QCFilter == \"Keep\" & Sample == 1) \ntable(colnames(ref.sce) %in% cell_metadata$Barcode) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n 1409  8988 \n```\n\n\n:::\n\n```{.r .cell-code}\nref.sce <- ref.sce[, cell_metadata$Barcode]\ncolData(ref.sce) <- cbind(colData(ref.sce), cell_metadata)\n\n## Explore the annotated object\ndata(\"ditto_colors\")\nggcells(ref.sce, aes(x = UMAP1, y=UMAP2, color=Level1)) + \n  geom_point() +\n  scale_colour_manual(values = ditto_colors) + \n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/load_annot-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggcells(ref.sce, aes(x = UMAP1, y=UMAP2, color=Level2)) + \n  geom_point() +\n  scale_colour_manual(values = ditto_colors) + \n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/load_annot-2.png){width=672}\n:::\n:::\n\n\n::: callout-important\n### Exercise 3\nWhat do you observe?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n### Answer\nThe cell types match the expectations based on the tissue sample we could study earlier in the course. It includes tumore cells, stromal cells and immune cells.\n\nA few cells in the dataset could be misannotated, although this might be an impression induced by the distortion typical of dimensionality reductions like UMAP.\n:::\n\n## Perform the anotation with `SingleR`\n\nTo annotate each cell, we use the `SingleR()` method, which uses a correlation-based approach comparing cells from the Visium HD dataset to reference cells from the FLEX dataset with known cell-type annotation.\n\nWe will use below the highest-level annotation available. A pseudo-bulk aggregation step before the comparison allows for a better performance. We also disable the fine tuning setp for faster computation here:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(colData(ref.sce)$Level1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n              B cells           Endothelial            Fibroblast \n                  990                   309                  1058 \nIntestinal Epithelial               Myeloid              Neuronal \n                  252                  1120                    32 \n        Smooth Muscle               T cells                 Tumor \n                  297                  1250                  3680 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Predict cell-type using SingleR \npred <- SingleR(test = sfe,\n                ref = ref.sce,\n                labels = ref.sce$Level1,\n                aggr.ref = TRUE,       \n                fine.tune = FALSE,     \n)\nsfe$SingleR_label <- pred$pruned.labels\ntable(sfe$SingleR_label)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n              B cells           Endothelial            Fibroblast \n                 3616                  2546                  8377 \nIntestinal Epithelial               Myeloid              Neuronal \n                 5057                  2296                    34 \n        Smooth Muscle               T cells                 Tumor \n                  942                   906                  9989 \n```\n\n\n:::\n\n```{.r .cell-code}\n# visualize the predictions on the tissue slide.\nplotSpatialFeature(sfe,  \n                   colGeometryName = \"cellSeg\",\n                   features = \"SingleR_label\")\n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/day2-4-annotation-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## Or on the UMAP\nggcells(sfe, aes(x = UMAP.1, y=UMAP.2, color=SingleR_label)) + \n  geom_point() +\n  scale_colour_manual(values = ditto_colors) + \n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/day2-4-annotation-3-2.png){width=672}\n:::\n:::\n\n\n:::{.callout-important}\n### Exercise 4\nWhat do you think about this annotation? \n\nHow do the proportions of different cell types compare to the annotated scRNA-seq dataset?\n\nDo you identify potentially relevant biological structures? Go back to the calculated clusters and spatial domains, to see how do they match.\n\nTry annotating the dataset with the higher-resolution cell-types lables in `ref.sce$Level2`\n:::\n\n:::{.callout-tip collapse=\"true\"}\n### Answer\nLet's calculate the proportion of cells from each cell type:\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(table(ref.sce$Level1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n              B cells           Endothelial            Fibroblast \n          0.110146862           0.034379172           0.117712506 \nIntestinal Epithelial               Myeloid              Neuronal \n          0.028037383           0.124610592           0.003560303 \n        Smooth Muscle               T cells                 Tumor \n          0.033044059           0.139074321           0.409434802 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(table(sfe$SingleR_label))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n              B cells           Endothelial            Fibroblast \n           0.10709949            0.07540799            0.24811184 \nIntestinal Epithelial               Myeloid              Neuronal \n           0.14977934            0.06800344            0.00100702 \n        Smooth Muscle               T cells                 Tumor \n           0.02790036            0.02683411            0.29585641 \n```\n\n\n:::\n:::\n\nWe observe a relatively higher proportion of Endothelial cells and Fibroblast in the Visium HD. Maybe such cell-types are less easily captured by the droplet-based scRNA-seq technology?\n\nThe annotation allows us to identify the different structures of the [intestine mucosa](https://en.wikipedia.org/wiki/Intestinal_villus) very clearly, with the epithelial cells composing the intestinal villi, the smooth muscle layer, and the more scattered immune cells. In this colorectal cancer sample, the invading tumor is identified very clearly. \n\n\nLet's compare the annotation to the Leiden clustering for example:\n\n::: {.cell}\n\n```{.r .cell-code}\nplotSpatialFeature(sfe,  \n                   colGeometryName = \"cellSeg\",\n                   features = \"SingleR_label\") +\n  plotSpatialFeature(sfe,  \n                   colGeometryName = \"cellSeg\",\n                   features = \"Leiden\")\n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/day2-4-annotation-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## For a more formal comparison\ntab_prop <- prop.table(table(sfe$Leiden, sfe$SingleR_label), margin = 1)\n## Display the proportions: round and remove 0s\nnum_mat <- round(tab_prop, 2)\nnum_mat[num_mat == 0] <- \"\"\n\npheatmap(\n  tab_prop,\n  cluster_rows = TRUE,\n  cluster_cols = TRUE,\n  color = viridis(100, option = \"magma\", direction = -1),\n  display_numbers = num_mat,\n  main = \"Leiden clusters vs. SingleR labels\", \n  annotation_colors = list(SingleR_label = setNames(object = ditto_colors[1:9], colnames(tab_prop)))  \n)\n```\n\n::: {.cell-output-display}\n![](day2-4_annotation_files/figure-html/day2-4-annotation-5-2.png){width=672}\n:::\n:::\n\n:::\n\n:::{.callout-important}\n\n## Exercise 5: Xenium (Bonus)\n\nPerform the same annotation task on the Xenium dataset. How do the results compare? What could be a limitation here?\n:::\n\n:::{.callout-tip collapse=\"true\"}\n### Answer\n\nOne limitation of this Xenium dataset is the limited number of genes targeted by the probe panel. Some recent benchmarks seem to suggest that the classical scRNA-seq annotation methods (label-transfer methods) perform relatively well: https://link.springer.com/article/10.1186/s12859-025-06044-0\n\n:::\n\n:::{.callout-important}\n\n## Exercise 6: RCTD (Bonus)\n\nWe ignored the fact that segmented data suffer from segmentation error, that multiple cells can overlap on the slide, and that spatial data in general suffers from local diffusion of transcripts. All these result in contamination of each cell's transcriptome with transcripts from other cells. \n\nIt is possible to use deconvolution methods to \"decontaminate\" the cells. For example the RCTD method from the `spacexr` package ([Cable _et al._ 2022](https://www.nature.com/articles/s41587-021-00830-w)) can be used in flag these cases and provide a principled estimate of the most likely composition. Try to run this method on our dataset, you can refer to [this section of the OSTA book](https://bioconductor.org/books/release/OSTA/pages/seq-deconvolution.html#rctd) for guidance. \n\nHow do you interpret the results?\n\n:::\n\n:::{.callout-tip collapse=\"true\"}\n### Answer\n\nSee the vignette here: https://raw.githack.com/dmcable/spacexr/master/vignettes/spatial-transcriptomics.html\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Install latest version from Github\nBiocManager::install(\"dmcable/spacexr\")\nlibrary(spacexr)\nsort(table(ref.sce$Level2))\n## We need a minimum of 25 cells for each cell type in the reference, so we'll go for Level1 here\nreference <- Reference(counts(ref.sce), \n                       cell_types=setNames(factor(ref.sce$Level1), nm = colnames(ref.sce)), \n                       nUMI=colSums(counts(ref.sce)))\n## Create SpatialRNA object\nto_annotate <- SpatialRNA(coords=data.frame(spatialCoords(sfe)), \n                          counts=counts(sfe),\n                          nUMI=colSums(counts(sfe)))\nrctd_data <- create.RCTD(to_annotate, reference)\n\n## Run RCTD\nres <- run.RCTD(rctd_data, doublet_mode=\"doublet\")\n## We use here the \"doublet\" mode to fit at most two cell types per segmented cell, probably this is a reasonable assumption for a high-resolution technology such as Visium HD.\n\n## Inspect results\nresults <- res@results\n# normalize the cell type proportions to sum to 1.\nnorm_weights <- normalize_weights(results$weights) \ncell_type_names <- res@cell_type_info$info[[2]] #list of cell type names\n\n# Plots the confident weights for each cell type as in full_mode (saved as \n# 'results/cell_type_weights.pdf')\nplot_weights(cell_type_names, to_annotate, \"./results/\", norm_weights) \n\n## Likely \"doublets\"\nsfe$RCTD.doublet <- NA\ncolData(sfe)[row.names(results$results_df), ]$RCTD.doublet <- as.character(results$results_df$spot_class)\nplotSpatialFeature(sfe,  \n                   colGeometryName = \"cellSeg\",\n                   features = \"RCTD.doublet\") \n\n## Extract major cell type\nsfe$RCTD.first <- NA\ncolData(sfe)[row.names(results$results_df), ]$RCTD.first <- as.character(results$results_df$first_type)\nplotSpatialFeature(sfe,  \n                   colGeometryName = \"cellSeg\",\n                   features = \"RCTD.first\") \n\n## Plotting the normalized weights for each cell type\nlapply(colnames(norm_weights), \\(k) {\n    colData(sfe)$foo <- NA\n    colData(sfe)[row.names(norm_weights), ]$foo <- norm_weights[, k]\n    plt <- plotSpatialFeature(sfe, features = \"foo\") + \n      scale_color_gradientn(colors=pals::jet())\n    plt + ggtitle(k) + guides(fill=\"none\")\n}) |>\n  wrap_plots(nrow=3)\n```\n:::\n\n\n<!-- \nWeird vertical line, esp. visible for epithelial, fibroblast... Is this a tile boundary? \n-->\n\n:::\n\n\n## Saving the final `SpatialFeatureExperiment` object\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalabaster.sfe::saveObject(sfe, \"results/day2/02.4_sfe\")\n```\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}